[package]
name = "spurs"
version = "0.1.0"
authors = ["Mark Mansi <markm@cs.wisc.edu>"]
edition = "2018"

[dependencies]
ssh2 = "0.3.3"
dirs = "1.0.4"
failure = "0.1.2"
failure_derive = "0.1.2"
console = "0.6.2"
